### ISSUE TITLE
칵테일 검색 기능 구현

### ISSUE THREAD

**Issue by jisu-0305** [Minjae-An/Cockpybara#10]
### To-do

- [x] 검색 필터 제공 API 
- [x] 단순 이름 기반 검색
- [x] 이름 + 필터(카테고리, 글라스 등) 기반 검색

**Comment by Minjae-An** [comment]
개발 완료

**Comment by Minjae-An** [comment]
작업 완료
